### ISSUE TITLE
Instalação do ambiente

### ISSUE THREAD

**Issue by fsousac** [fga-eps-mds/2023.1-CanvLight-Canvas-Inteligente#1]
Respondam essa issue se já conseguiram organizar o ambiente de mds

**Comment by fsousac** [comment]
Já consegui organizar dps de muita luta pra fazer o dual boot

**Comment by brenoalexandre0** [comment]
dual boot eu ja tinha feito antes da matéria, entao ja tinha uma experiencia com linux. Tbm ja tenho uma experiencia com git.

**Comment by brunotarquinio** [comment]
dual boot feito há quase um ano, tenho boa experiência com linux

**Comment by HeBatalha** [comment]
Linux instalado com sucesso.

**Comment by raquel-andrade** [comment]
Ambiente ok

**Comment by LimirioGuimaraes** [comment]
Ambientes de desenvolvimento e comunicação instalados :)
