### ISSUE TITLE
Procurando framework e bibliotecas para o front end

### ISSUE THREAD

**Issue by pkbceira03** [fga-eps-mds/2023.1-CanvLight-Canvas-Inteligente#16]
## Descrição

Estudo de bibliotecas e framework para facilitar o desenvolvimento do frond end da nossa aplicação

## Elm 
É uma linguagem e estrutura funcional voltada para o desenvolvimento de front-end. É a fonte da linguagem de programação Haskell e aprimora a capacidade de manutenção do JavaScript.

É uma das opções mais próximas do JavaScript e uma opção de desenvolvimento simples. Elm apresenta uma arquitetura de estrutura semelhante ao Redux.

Recursos

Funcional – Elm oferece funções, entradas e saídas limpas para as necessidades dos desenvolvedores. Os usuários obtêm uma saída previsível para qualquer entrada de função fornecida. O raciocínio do código se torna mais fácil.
Reativo – os usuários do Elm podem definir interfaces de usuário com uma função devido ao suporte de programação reativa. Eles podem criar um ciclo reativo por meio de atualizações de ação do usuário.
Compila para JavaScript – Elm compila código para JavaScript para criação de HTML e CSS, permitindo que os navegadores executem o código.

Vantagens

Fácil de aprender – Elm é uma linguagem fácil de aprender, e os desenvolvedores podem acessar facilmente muitas dicas, guias, perguntas frequentes e outros recursos, junto com uma comunidade de desenvolvedores de suporte. O número e a variedade de recursos disponíveis estão crescendo rapidamente para ajudar os desenvolvedores.
Suporte mais fácil a projetos – Elm é conhecido pelo suporte fácil a projetos que oferece aos usuários devido aos avisos do compilador. Os avisos interrompem todas as alterações que um aplicativo não pode compilar. Isso leva à redução dos custos do projeto.

Desvantagens

Elm pode parecer restritivo para alguns desenvolvedores que estão acostumados com linguagens dinâmicas como JavaScript ou Ruby.
Além disso, Elm não tem nenhum suporte para cada ou para loops, e os usuários têm que fazer com algumas funções. Modificar um valor presente em uma estrutura aninhada pode ser um incômodo, pois o valor não pode ser alterado.

## Angular 
É uma estrutura de código aberto usada principalmente para o desenvolvimento de aplicativos da web de página única. Os desenvolvedores podem confiar nele para gerar menus animados adequados para páginas da web em HTML.

É uma estrutura desenvolvida pelos engenheiros do Google Adam Abrons e Misko Hebert. Lançado pela primeira vez em 2012, o AngularJS continua recebendo atualizações.

Recursos

Aplicativos da web progressivos – os desenvolvedores podem usar recursos de plataforma de ponta para criar experiências semelhantes aos aplicativos. Angular oferece alto desempenho e fácil instalação.
Angular CLI – o Angular oferece ferramentas de linha de comando para permitir que os desenvolvedores criem aplicativos com mais rapidez, adicionem testes e alcancem uma implantação rápida.

Vantagens

Funcionalidade pronta para uso – A configuração Angular padrão oferece um grande número de ferramentas para os desenvolvedores começarem. Alguns deles incluem ferramentas que podem ser usadas para atender aos requisitos de roteamento. Os desenvolvedores podem usá-lo para buscar os dados necessários que possuem em um aplicativo. A natureza pré-configurada do ambiente do Angular ajuda a acelerar o desenvolvimento e os testes.
Consistência – o Angular é uma estrutura de design de web abrangente e responsiva em comparação com o React. Os desenvolvedores podem achar fácil desenvolver serviços, componentes e módulos.

Desvantagens

Opções limitadas de SEO – Os usuários angulares enfrentam alguns problemas devido ao menor número de opções de SEO e não oferecem um alto nível de acessibilidade do rastreador de mecanismo de pesquisa.
Angular pode ser complexo – Angular pode ser considerado uma opção complexa por muitos desenvolvedores e pode impactar os resultados do desenvolvimento. Mesmo as versões recentes do Angular são complexas para alguns usuários.

## JQuery 
É uma biblioteca JavaScript objetiva, mas repleta de recursos. É uma opção viável para funções como tratamento de eventos, passagem de HTML, Ajax, manipulação de documentos e animações.

Os usuários também acham a API do jQuery muito fácil de usar e funciona em diferentes navegadores de forma eficaz. Essa linguagem de desenvolvimento de front-end é conhecida por sua flexibilidade e variedade de recursos. Ele permitiu que inúmeros desenvolvedores tirassem o máximo proveito da programação JavaScript.

Recursos

Manipulação CSS: jQuery tem métodos css () predefinidos para alterar o estilo do elemento HTML.
Manipulação de HTML: jQuery facilita a seleção, passagem e modificação de conteúdo de elementos DOM.
Suporte para vários navegadores: o jQuery fornece suporte para os navegadores modernos mais populares.

Vantagens

O jQuery permite a melhoria do JavaScript sem que os desenvolvedores tenham que aprender uma sintaxe nova.
O código pode ser simples, legível e reutilizável com jQuery.
A necessidade de escrever loops complexos e repetitivos e chamadas de biblioteca DOM é reduzida com a linguagem.

Desvantagens

A funcionalidade pode ser limitada – a funcionalidade do jQuery pode ser bastante limitada, embora tenha uma vasta biblioteca. O problema surge quando a necessidade de customização aumenta e os desenvolvedores dependem do JavaScript.
JQuery javascript needed – O arquivo jQuery JavaScript é necessário para executar comandos JQuery. Apesar do pequeno tamanho desse arquivo, é uma preocupação para um computador cliente e servidor web quando o requisito é hospedar scripts jQuery no servidor.

## Conclusão
A que achei mais interessante é o Jquery que acho que no momento pra gente é a que mais faz sentindo, por ter mais suporte de ser um pouco mais simples que as outras.

**Comment by fsousac** [comment]
Acho interessante dar uma olhada em React JS, se assemelha muito ao clássico HTML e CSS e de dar uma otimização no nosso projeto
