### ISSUE TITLE
Documento de Visão

### ISSUE THREAD

**Issue by HeBatalha** [fga-eps-mds/2023.1-CanvLight-Canvas-Inteligente#17]
# Documento de Visão 👁️ 

O Documento de Visão é o documento em que se define a visão geral de um produto ou projeto, nele são descritos os problemas, soluções e principais requisitos. Ou seja, toda a base lógica daquilo que vai ser desenvolvido, com base nas necessidades do usuário.
O documento de visão é geralmente criado no início do ciclo de vida do projeto e serve como um guia para a equipe do projeto, fornecendo uma compreensão clara do que deve ser construído, permitindo que eles trabalhem em direção a um objetivo comum e evitem desvios do escopo original.

## O que um Documento de Visão pode ter?

1. **Proposito do projeto** - O motivo e qual o seu proposito. 
2. **Escopo do projeto** - Definir com clareza o que deve ser realizado e os limites do projeto.
3. **Descrição do problema** - Descrever o que é, como afeta e uma solução.
4. **Descrição dos usuários** - Definir o público-alvo.
5. **Perfil dos usuários** - Definir as funções dos usuários.
6. **Requisitos funcionais** - Principais requisitos para o sistema, organizados por prioridade.
7. **Restrições** - Condições para o projeto.
8. **Requisitos Não Funcionais** - São requisitos que não são funcionalidades, mas são relacionados com a qualidade do produto.

## Diferenças entre o Documento de Visão e o Documento de Arquitetura

O Documento de Visão descreve a visão geral do produto, seus objetivos e principais requisitos, por outro lado, o Documento de Arquitetura se concentra na estrutura, componentes, tecnologias e padrões que serão usados no desenvolvimento do produto.
Por isso o Documento de Arquitetura é geralmente criado após o documento de visão, pois requer uma compreensão clara dos requisitos do sistema e das funcionalidades que serão implementadas.

# Documento de Arquitetura 📐 

O documento de arquitetura em um projeto de software é um documento que descreve a arquitetura do sistema a ser desenvolvido. Ele é importante porque fornece uma visão geral da estrutura do sistema e ajuda a garantir que o sistema seja desenvolvido de forma consistente e eficiente.

## Conteúdo do Documento de Arquitetura

O documento de arquitetura deve incluir informações sobre:

- A estrutura do sistema, incluindo componentes, módulos, camadas e interfaces;
- As tecnologias e padrões utilizados;
- As restrições e requisitos arquitetônicos do sistema, incluindo requisitos de desempenho, escalabilidade, segurança e confiabilidade;
- As decisões arquitetônicas tomadas, incluindo as justificativas para essas decisões.

## Importância do Documento de Arquitetura

O documento de arquitetura é importante porque:

- Ajuda a garantir que todos os envolvidos no desenvolvimento do sistema tenham uma compreensão clara da arquitetura e possam trabalhar juntos de forma eficiente;
- Permite que o sistema seja desenvolvido de forma consistente e eficiente;
- Garante que as restrições e requisitos arquitetônicos sejam considerados desde o início do desenvolvimento do sistema;
- Facilita a manutenção do sistema ao longo do tempo;
- Ajuda a reduzir os riscos associados ao desenvolvimento do sistema.

## Atualização do Documento de Arquitetura

O documento de arquitetura deve ser atualizado conforme o sistema é desenvolvido e evolui. Isso garante que a documentação esteja sempre atualizada e que todos os envolvidos no projeto tenham acesso às informações mais recentes sobre a arquitetura do sistema.

## Conclusão

Em resumo, o documento de arquitetura é um documento importante que descreve a estrutura e os requisitos arquitetônicos do sistema a ser desenvolvido, bem como as decisões arquitetônicas tomadas. Ele é essencial para garantir que o sistema seja desenvolvido de forma consistente e eficiente e que todos os envolvidos no projeto tenham uma compreensão clara da arquitetura do sistema.

**Comment by brenoalexandre0** [comment]
# Documento de Arquitetura

O documento de arquitetura em um projeto de software é um documento que descreve a arquitetura do sistema a ser desenvolvido. Ele é importante porque fornece uma visão geral da estrutura do sistema e ajuda a garantir que o sistema seja desenvolvido de forma consistente e eficiente.

## Conteúdo do Documento de Arquitetura

O documento de arquitetura deve incluir informações sobre:

- A estrutura do sistema, incluindo componentes, módulos, camadas e interfaces;
- As tecnologias e padrões utilizados;
- As restrições e requisitos arquitetônicos do sistema, incluindo requisitos de desempenho, escalabilidade, segurança e confiabilidade;
- As decisões arquitetônicas tomadas, incluindo as justificativas para essas decisões.

## Importância do Documento de Arquitetura

O documento de arquitetura é importante porque:

- Ajuda a garantir que todos os envolvidos no desenvolvimento do sistema tenham uma compreensão clara da arquitetura e possam trabalhar juntos de forma eficiente;
- Permite que o sistema seja desenvolvido de forma consistente e eficiente;
- Garante que as restrições e requisitos arquitetônicos sejam considerados desde o início do desenvolvimento do sistema;
- Facilita a manutenção do sistema ao longo do tempo;
- Ajuda a reduzir os riscos associados ao desenvolvimento do sistema.

## Atualização do Documento de Arquitetura

O documento de arquitetura deve ser atualizado conforme o sistema é desenvolvido e evolui. Isso garante que a documentação esteja sempre atualizada e que todos os envolvidos no projeto tenham acesso às informações mais recentes sobre a arquitetura do sistema.

## Conclusão

Em resumo, o documento de arquitetura é um documento importante que descreve a estrutura e os requisitos arquitetônicos do sistema a ser desenvolvido, bem como as decisões arquitetônicas tomadas. Ele é essencial para garantir que o sistema seja desenvolvido de forma consistente e eficiente e que todos os envolvidos no projeto tenham uma compreensão clara da arquitetura do sistema.
