### ISSUE TITLE
Estudo sobre métodos ágeis

### ISSUE THREAD

**Issue by HeBatalha** [fga-eps-mds/2023.1-CanvLight-Canvas-Inteligente#6]
Método Scrum:
[Scrum.pdf](https://github.com/fga-eps-mds/2023.1-Canvas-Inteligente/files/11250758/Scrum.pdf)
https://docs.google.com/document/d/e/2PACX-1vQ-Qsfc5mAXKYd37jLGd7YAPEpfS5Ke3OOz3j4nr133FHFlBoO4rRZBj_rAXJy_WtkI1e1uYx_tnhIA/pub

**Comment by HeBatalha** [comment]
@pkbceira03 e @brunotarquinio vocês podem usar essa issue também

**Comment by brunotarquinio** [comment]
Método Extreme Programming (XP):

https://docs.google.com/document/d/1fal-SanASrCNZBkshQtM5Ik21JAA3bi2hdHj-SjzI70/edit?usp=drivesdk

**Comment by pkbceira03** [comment]
kanban:
https://docs.google.com/document/d/1xsGSwjfSQE06C9Iq-psj2Zz5F3y9t16Tw0isRDaArCo/edit?usp=sharing
