### ISSUE TITLE
Finalizando responsividade para R2

### ISSUE THREAD

**Issue by fsousac** [fga-eps-mds/2023.1-CanvLight-Canvas-Inteligente#74]
## Descrição

Continuando a responsividade e estilização do css para a Realise 2, Continuação da issue #68 

### Observação 2

![Captura de tela 2023-07-13 - 16 21 37](https://github.com/fga-eps-mds/2023.1-CanvLight-Canvas-Inteligente/assets/95441810/1cf93f99-d732-4dc5-a301-e08b5fce78bf)

### Observação 3

![Captura de tela 2023-07-13 - 16 21 44](https://github.com/fga-eps-mds/2023.1-CanvLight-Canvas-Inteligente/assets/95441810/c560b614-eb98-4082-860d-ed73f507e2f7)

### Interação 1

![Captura de tela 2023-07-13 - 16 25 29](https://github.com/fga-eps-mds/2023.1-CanvLight-Canvas-Inteligente/assets/95441810/b2c2a1e9-717d-4279-b43b-85aec4e189a8)

### Interação 3

![Captura de tela 2023-07-13 - 16 25 43](https://github.com/fga-eps-mds/2023.1-CanvLight-Canvas-Inteligente/assets/95441810/9bcb2bfc-6071-463e-8609-55a781aee6e4)

### Maturidade 1

![Captura de tela 2023-07-14 - 16 45 23](https://github.com/fga-eps-mds/2023.1-CanvLight-Canvas-Inteligente/assets/95441810/81195c46-7e7a-4fbe-9499-efecdb8b3d9f)

### Maturidade 2

![Captura de tela 2023-07-14 - 16 45 27](https://github.com/fga-eps-mds/2023.1-CanvLight-Canvas-Inteligente/assets/95441810/13b327a6-7f5f-46a3-8aa9-63ee32bab0a7)

### Maturidade 3

![Captura de tela 2023-07-14 - 16 45 32](https://github.com/fga-eps-mds/2023.1-CanvLight-Canvas-Inteligente/assets/95441810/506aa054-e2ea-4e90-a6b4-4dfe91631792)

### Maturidade 4

![Captura de tela 2023-07-14 - 16 45 37](https://github.com/fga-eps-mds/2023.1-CanvLight-Canvas-Inteligente/assets/95441810/27e4be42-f830-4141-82a2-f0fc2f69f832)

### Maturidade 5

![Captura de tela 2023-07-14 - 16 46 56](https://github.com/fga-eps-mds/2023.1-CanvLight-Canvas-Inteligente/assets/95441810/4c2650f2-b35b-4708-b900-3f791ed090d6)

## Checklist

- [x] Tornar a Observação responsiva.
- [x] Tornar a Interação responsiva.
- [x] Tornar a Maturidade responsiva.

**Comment by LimirioGuimaraes** [comment]
Issue finalizada!
